# config.yaml (兼容新版 train.py，保留原始参数值)
dataset:
  metadata_path: "/openbayes/home/CharacterRepaint/scripts/CIRI_syth_metadata.json"
  batch_size: 12
  num_workers: 2

model_params:
  image_size: 288
  in_channels: 1
  out_channels: 1
  model_channels: 64
  channel_mult: [1, 2, 4, 8]
  num_res_blocks: 2
  time_emb_dim_ratio: 4
  groups: 32

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

training_params:
  epochs: 100
  lr: 0.0001
  scheduler:
    name: "StepLR"
    step_size: 25
    gamma: 0.35
  output_dir: "/openbayes/home/CharacterRepaint/train_output/003-20250701-11:46_new_dataset"
  save_checkpoint_freq: 100
  save_visualization_freq: 5
  device: "cuda"

# <<<< 结构调整以适配新版 train.py >>>>
visualization_params:
  # 此参数依然有效，决定了验证批次的大小和可视化网格的宽度
  num_samples_to_visualize: 4
  
  # <<<< 新增的必需参数 >>>>
  # 用于控制可视化采样时的修复强度。
  # 我们需要为它提供一个默认值，250 是一个合理的开始。
  start_timestep: 250
  
  # <<<< 不再使用的参数（可以安全删除或注释掉） >>>>
  # fixed_noise_for_samples: True # 新的采样逻辑不再使用固定的噪声图